<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:t="http://www.tei-c.org/ns/1.0" xmlns:h="http://www.w3.org/1999/xhtml" version="2.0" exclude-result-prefixes="t h xsl">
    <!-- Hent salmetekster fra TEI til korrekturlæsning -->
    
    <!-- Det Danske Sprog- og Litteraturselskab, 2019 -->
    <!-- http://www.dsl.dk --><xsl:output xml:space="default" method="xml" encoding="UTF-8" omit-xml-declaration="no"/><xsl:param name="file"/><xsl:template match="/"><div xmlns="http://www.w3.org/1999/xhtml"><a name="start" id="start" tabindex="0"/><xsl:apply-templates select="node()"/><a name="end" id="end" tabindex="99999"/></div></xsl:template>
    
    <!--<xsl:template match="t:div[@type='psalm']">--><xsl:template match="t:div[@type='psalm' or t:notatedMusic]"><xsl:element xmlns="http://www.w3.org/1999/xhtml" name="div"><xsl:for-each select="@*"><xsl:attribute name="{local-name()}"><xsl:value-of select="."/></xsl:attribute></xsl:for-each><xsl:apply-templates select="*" mode="tei_to_html"/></xsl:element></xsl:template>
    
    <!-- skip most things --><xsl:template match="node()"><xsl:apply-templates select="node()"/></xsl:template><xsl:template match="t:c | t:lb | t:space | t:title" mode="tei_to_html"><xsl:apply-templates select="node()" mode="tei_to_html"/></xsl:template>
    
    <!-- delete some things --><xsl:template match="t:figure | t:notatedMusic | t:head[@type='add']" mode="tei_to_html"/>

    <!-- show first stanza only --><xsl:template match="t:lg[ancestor::*/t:notatedMusic and position() &gt; 1]" mode="tei_to_html">
        <!-- get only page breaks from other stanzas than the first --><xsl:apply-templates select=".//t:pb" mode="tei_to_html"/></xsl:template>
    
    <!-- change things --><xsl:template match="t:pb[ancestor::*/t:notatedMusic]"><xsl:apply-templates select="." mode="tei_to_html"/></xsl:template><xsl:template match="t:pb" mode="tei_to_html">
        <!-- turn page breaks into HTML anchors --><xsl:element xmlns="http://www.w3.org/1999/xhtml" name="a">
            <!--<xsl:variable name="file" select="'thomissoen_1569.xml'"/>-->
            <!-- try to guess the corresponding page number --><xsl:variable name="a"><xsl:choose><xsl:when test="$file='thomissoen_1569.xml'"><xsl:variable name="fol" select="round((number(translate(@n,'E','')) - 56) div 2)"/><xsl:variable name="side"><xsl:choose><xsl:when test="number(translate(@n,'E','')) mod 2 &gt; 0">r</xsl:when><xsl:otherwise>v</xsl:otherwise></xsl:choose></xsl:variable><xsl:value-of select="concat(substring('000',1,3-string-length(string($fol))),$fol,$side)"/></xsl:when><xsl:when test="$file='jespersen_1573.xml'"><xsl:variable name="side" select="number(translate(@n,'E','')) - 12"/><xsl:value-of select="concat(substring('000',1,3-string-length(string($side))),$side)"/></xsl:when><xsl:otherwise>-</xsl:otherwise></xsl:choose></xsl:variable><xsl:attribute name="tabindex"><xsl:value-of select="translate($a,'rv','')"/></xsl:attribute><xsl:attribute name="name"><xsl:value-of select="$a"/></xsl:attribute><xsl:attribute name="onclick">goto('mei_<xsl:value-of select="$a"/>');</xsl:attribute><xsl:attribute name="id"><xsl:value-of select="$a"/></xsl:attribute><xsl:attribute name="n"><xsl:value-of select="@n"/></xsl:attribute><xsl:attribute name="title">Sideskift</xsl:attribute><xsl:attribute name="style">text-decoration:none;</xsl:attribute><xsl:text>[</xsl:text><xsl:value-of select="$a"/><xsl:text>]</xsl:text></xsl:element></xsl:template><xsl:template match="t:row" mode="tei_to_html"><xsl:element xmlns="http://www.w3.org/1999/xhtml" name="tr"><xsl:apply-templates mode="tei_to_html"/></xsl:element></xsl:template><xsl:template match="t:cell" mode="tei_to_html"><xsl:element xmlns="http://www.w3.org/1999/xhtml" name="td"><xsl:apply-templates mode="tei_to_html"/></xsl:element></xsl:template><xsl:template match="t:lg" mode="tei_to_html"><xsl:element xmlns="http://www.w3.org/1999/xhtml" name="p"><xsl:apply-templates mode="tei_to_html"/></xsl:element></xsl:template><xsl:template match="t:l" mode="tei_to_html"><xsl:element xmlns="http://www.w3.org/1999/xhtml" name="span"><xsl:apply-templates mode="tei_to_html"/><xsl:if test="not(position()=last())"><br/></xsl:if></xsl:element></xsl:template><xsl:template match="t:head" mode="tei_to_html"><xsl:element xmlns="http://www.w3.org/1999/xhtml" name="p"><xsl:apply-templates select="@*" mode="tei_to_html"/><b><xsl:apply-templates select="node()" mode="tei_to_html"/></b></xsl:element></xsl:template>
    
    
    <!-- move other things to HTML namespace --><xsl:template match="text()" mode="tei_to_html"><xsl:copy-of select="."/></xsl:template><xsl:template match="@*" mode="tei_to_html"><xsl:attribute name="{local-name()}"><xsl:value-of select="."/></xsl:attribute></xsl:template><xsl:template match="*" mode="tei_to_html"><xsl:element name="{local-name()}"><xsl:apply-templates select="@* | node()" mode="tei_to_html"/></xsl:element></xsl:template></xsl:stylesheet>